### ISSUE TITLE
Create the Job Card (Light Mode Only)

### ISSUE THREAD

**Issue by wpslck** [unocorn-squad/job-posting-app#11]
Implement and style a responsive Job Details Card component that supports all device sizes (mobile, tablet, and desktop). 

The job card should have to following:

- [ ] Company logo
- [ ] Job posted time
- [ ] Full time / Part time
- [ ] Company name
- [ ] Job location

Desktop-view 

![Image](https://github.com/unocorn-squad/job-posting-app/assets/11665833/240ca731-5cab-4ade-b27f-7a37a907ba40)

**Comment by jpmaHub** [comment]
There is a separate task for Job Details Card and i think this one is just Job Card?
