### ISSUE TITLE
Implement Job Title and Location Search Functionality

### ISSUE THREAD

**Issue by deeptijnair** [unocorn-squad/job-posting-app#2]
Enhance the existing `SearchBar` component to allow users to filter job postings by Job Title and Job Location.

### Requirements:
1. Use the existing `SearchBar` component:
   - Left input box: job title search
   - Right input box: job location search

2. Search Behavior:
   - Implement partial match searching for both fields
   - Make searches case-insensitive
   - Perform search when users click on the "Search" button

3. Filtering Logic:
   - Job Title: Match against the job posting's title field
   - Job Location: Match against the job posting's location field
   - If both fields are used, results should satisfy both criteria (AND operation)

4. Results Display:
   - Update the job listings when the user clicks on the button to show only matching results
   - If no results match the search criteria, display a "No results found" message

6. Edge Cases:
   - Handle empty input fields (show all results when both fields are empty)
   - Properly handle special characters and whitespace in search inputs

7. Accessibility:
   - Ensure the search functionality is fully accessible via keyboard
   - Add appropriate ARIA labels to improve the screen reader experience

**Comment by wpslck** [comment]
This task is dependent on #36. Please see PR on the task progress: https://github.com/unocorn-squad/job-posting-app/pull/40.
