### ISSUE TITLE
Style Bulleted & Numbered Lists

### ISSUE THREAD

**Issue by wpslck** [unocorn-squad/job-posting-app#22]
![Image](https://github.com/unocorn-squad/job-posting-app/assets/16579792/98bb43a4-c5bf-4650-8058-710eb99da634)

![Image](https://github.com/unocorn-squad/job-posting-app/assets/16579792/d5f5396e-501d-47ef-a021-60e72767fcc0)

**Comment by eileenxue** [comment]
@jennyychaa Oh maybe I can grab this ticket as well, I'm trying to wrap up my job details component and that's one of the the last parts I needed to style.

![Image](https://github.com/unocorn-squad/job-posting-app/assets/16721486/3272f623-47ec-40ba-b261-170d758d4378)
