### ISSUE TITLE
Implement "Load More" functionality for job postings on Search page

### ISSUE THREAD

**Issue by deeptijnair** [unocorn-squad/job-posting-app#5]
Add a "Load More" button on the Search page to enable users to incrementally load additional job postings. 

### Requirements:
- Initial Display: Show the first 12 job postings by default.
- Button Placement: Add a "Load More" button at the bottom of the job listings.
- Functionality: When a user clicks the "Load More" button, fetch and display 6 additional job postings.
- Append vs. Replace: New postings should append to the existing list, not replace it.
- Loading State: Display a loading indicator (e.g., spinner) while fetching new postings.
- Empty State: If no more job postings are available, hide the "Load More" button. 

### Technical Considerations:
- Ensure the UI remains responsive during the loading process.
- Handle potential errors gracefully, displaying user-friendly error messages if fetching fails.

**Comment by wpslck** [comment]
Please update Jenny by end of the day Monday on the status of this task.
